In [2]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype = 'int64')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0], [5.0,4.0,3.0]])
print(b)

[[9. 8. 7.]
 [5. 4. 3.]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [14]:
a.dtype

dtype('int16')

In [12]:
b.dtype

dtype('float64')

In [17]:
a.itemsize

8

In [18]:
a.size * a.itemsize

24

In [19]:
a.nbytes

24

In [22]:
x = np.array([[0,1,2,3,4,5],[8,16,5,29,3,24]])
print(x)

[[ 0  1  2  3  4  5]
 [ 8 16  5 29  3 24]]


In [28]:
#get a specific element
x[1,2]

np.int64(5)

In [ ]:
#get a specific row
x[0,:]

array([0, 1, 2, 3, 4, 5])

In [30]:
#get a specific column
x[:,2]

array([2, 5])

In [35]:
#[startindex:endindex:stepsize]
x[0,1:5:1]

array([1, 2, 3, 4])

In [37]:
x[1,3] = 15
print(x)

x[:,3] = [1,4]
print(x)

[[ 0  1  2  3  4  5]
 [ 8 16  5 15  3 24]]
[[ 0  1  2  1  4  5]
 [ 8 16  5  4  3 24]]


In [38]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [51]:
b[0,1,1]
b[0,2,:]

array([5, 6])

In [ ]:
#replace
b[:,2,:] = [9,8]
print(b)

[[[1 2]
  [9 8]
  [9 8]
  [7 8]]]


In [62]:
#0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((4,2,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [68]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
#1s matrix
np.ones(3)

array([1., 1., 1.])

In [70]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
#any number
np.full((3,3),816,dtype = 'float32')


array([[816., 816., 816.],
       [816., 816., 816.],
       [816., 816., 816.]], dtype=float32)

In [77]:
#any other number (full_like)
np.full_like(b,8)

array([[[8, 8],
        [8, 8],
        [8, 8],
        [8, 8]]])

In [79]:
np.random.rand( 2,2,3)

array([[[0.80668833, 0.15555463, 0.48882352],
        [0.41904896, 0.58228188, 0.63836905]],

       [[0.96407126, 0.63573471, 0.47610551],
        [0.72431747, 0.6520957 , 0.40460943]]])

In [80]:
np.random.random_sample(a.shape)

array([0.63438695, 0.94248701, 0.57281444])

In [97]:
np.random.randint(3,5, size = (2,5))

array([[4, 4, 4, 4, 3],
       [3, 3, 4, 3, 4]], dtype=int32)

In [98]:
#identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#repeat the array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=1)
print(r)
x = np.repeat(arr,2, axis=0)
print(x)

[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [1 2 3]]


In [120]:
a = np.ones((5,5))
print(a)

b = np.zeros((3,3))
b[1,1] = 16
print(b)

a[1:-1,1:-1] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 0.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0. 16.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [126]:
a =np.array([5,6,7])
b = a.copy()
b[1] = 8
print(b)

[5 8 7]


Mathematics

In [127]:
#mathematics
a = np.array([4,5,6,7,8])
print(a)

[4 5 6 7 8]


In [128]:
a + 2

array([ 6,  7,  8,  9, 10])

In [129]:
a - 1

array([3, 4, 5, 6, 7])

In [130]:
a * 2

array([ 8, 10, 12, 14, 16])

In [131]:
a / 2

array([2. , 2.5, 3. , 3.5, 4. ])

In [132]:
a % 2

array([0, 1, 0, 1, 0])

In [ ]:
#adding 2 array
b = np.array([0,1,2,3,4])
a + b

array([ 4,  6,  8, 10, 12])

In [136]:
np.sin(a)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [137]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [138]:
np.cos(a)

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [139]:
np.matmul(a,b)

np.int64(70)

Linear algebra

In [147]:
#linear algebra
a = np.full((3,2), 2)
print(a)
b = np.full((2,3), 4)
print(b)

np.matmul(a,b)

[[2 2]
 [2 2]
 [2 2]]
[[4 4 4]
 [4 4 4]]


array([[16, 16, 16],
       [16, 16, 16],
       [16, 16, 16]])

In [ ]:
#fint the determinant
c = np.identity(5)
np.linalg.det(c)

np.float64(1.0)

In [154]:
x = np.array([[10,12,13],[14,15,16]])
print(x)

[[10 12 13]
 [14 15 16]]


In [ ]:
np.min(x) #o.p =10
np.min(x, axis=1)

array([10, 14])

In [160]:
np.max(x) #16
np.max(x, axis=1)

array([13, 16])

In [161]:
np.sum(x)

np.int64(80)

In [162]:
np.sum(x, axis=0)

array([24, 27, 29])

Reorganizing array

In [168]:
b = np.array([[0,1,2,3,4], [5,6,7,8,9]])
print(b)
c = b.reshape((10,1))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
#verticall stacking vectors
m = np.array([11,12,15,14,85])
a = np.array([65,25,33,47,16])
np.vstack([m,m,a,a,a])

array([[11, 12, 15, 14, 85],
       [11, 12, 15, 14, 85],
       [65, 25, 33, 47, 16],
       [65, 25, 33, 47, 16],
       [65, 25, 33, 47, 16]])

In [172]:
#horizontal stack
a = np.ones((2,3))
print(a)
b = np.zeros((2,2))
print(b)
np.hstack((a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [180]:
data = np.genfromtxt(r"C:\Users\balam\OneDrive\Documents\data.txt", delimiter=',')
data = data.astype('int32')
print(data)

[    1     2     3    45    52    41    45    65    85    47    96    33
    25   165    85  9291   801    10     8    16     3    84     2  2004
  2003  2022   523  5896   257 98944 26512]


In [187]:
data[data>50]

array([], dtype=bool)

In [188]:

np.any(data > 50, axis=0)



np.False_

In [183]:
data = np.any(data > 50, axis=0)
print(data)

True


In [189]:
((data > 50) & (data < 100))

np.False_